<%@ Page Title="Manage Characters - B.E.T.T.E.R" Language="C#" MasterPageFile="~/Member.Master" AutoEventWireup="true" CodeBehind="ManageCharacters.aspx.cs" Inherits="B.E.T.T.E.R.UL.ManageCharacters" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Manage Characters</h1>
    <div class="col-group">    
        <asp:GridView ID="ManageCharactersGridView" cssclass="TableGrid" GridLines="None" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" DataKeyNames="titanId" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
            <Columns>
                <asp:BoundField DataField="titanName" HeaderText="Titan Name" SortExpression="titanName"/>
                <asp:BoundField DataField="experience" HeaderText="XP" SortExpression="experience" ReadOnly="true" />
                <asp:BoundField DataField="creationDate" HeaderText="Date Created" SortExpression="creationDate" DataFormatString="{0:d}" ReadOnly="true" />
                <asp:ImageField DataImageUrlField="imagePath" ReadOnly="true">
                    <ControlStyle CssClass="GridViewImage" />
                </asp:ImageField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:udbBetterConnectionString %>" SelectCommand="SELECT [titanName], [experience], [creationDate], [titanId], [elementId], [imagePath] FROM [tblTitan] WHERE ([userId] = @userId AND [active] = @active)" DeleteCommand="DELETE FROM [tblTitan] WHERE [titanId] = @titanId" InsertCommand="INSERT INTO [tblTitan] ([titanName], [experience], [creationDate], [elementId]) VALUES (@titanName, @experience, @creationDate, @elementId)" UpdateCommand="UPDATE [tblTitan] SET [titanName] = @titanName WHERE [titanId] = @titanId" >
            <DeleteParameters>
                <asp:Parameter Name="titanId" Type="Int32" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="titanName" Type="String" />
                <asp:Parameter Name="experience" Type="Int32" />
                <asp:Parameter Name="creationDate" Type="DateTime" />
                <asp:Parameter Name="elementId" Type="Int32" />
                <asp:Parameter Name="titanId" Type="Int32" />
            </UpdateParameters>
            <SelectParameters>
                <asp:SessionParameter Name="userId" SessionField="userId" Type="Int32" />
                <asp:Parameter DefaultValue="true" Name="active" Type="Boolean" />
            </SelectParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
