<%@ Page Title="Manage Characters - B.E.T.T.E.R" Language="C#" MasterPageFile="~/Member.Master" AutoEventWireup="true" CodeBehind="ManageCharacters.aspx.cs" Inherits="B.E.T.T.E.R.UL.ManageCharacters" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h1>Manage Characters</h1>
    <div class="col-group">    
        <asp:GridView ID="GridView" cssclass="TableGrid" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" DataKeyNames="titanId">
            <Columns>
                <asp:BoundField DataField="titanName" HeaderText="Name" SortExpression="titanName"/>
                <asp:BoundField DataField="experience" HeaderText="Points" SortExpression="experience" ReadOnly="True" />
                <asp:BoundField DataField="creationDate" HeaderText="Date Created" SortExpression="creationDate" DataFormatString="{0:d}" ReadOnly="True" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:udbBetterConnectionString %>" SelectCommand="SELECT [titanName], [experience], [creationDate], [titanId], [elementId] FROM [tblTitan]" DeleteCommand="DELETE FROM [tblTitan] WHERE [titanId] = @titanId" InsertCommand="INSERT INTO [tblTitan] ([titanName], [experience], [creationDate], [elementId]) VALUES (@titanName, @experience, @creationDate, @elementId)" UpdateCommand="UPDATE [tblTitan] SET [titanName] = @titanName WHERE [titanId] = @titanId" >
            <DeleteParameters>
                <asp:Parameter Name="titanId" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="titanName" Type="String" />
                <asp:Parameter Name="experience" Type="Int32" />
                <asp:Parameter Name="creationDate" Type="DateTime" />
                <asp:Parameter Name="elementId" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="titanName" Type="String" />
                <asp:Parameter Name="experience" Type="Int32" />
                <asp:Parameter Name="creationDate" Type="DateTime" />
                <asp:Parameter Name="elementId" Type="Int32" />
                <asp:Parameter Name="titanId" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>
</asp:Content>
